### ISSUE TITLE
vrpn_client_ros node crashes when echoing the topic that gives the object acceleration given by the vicon

### ISSUE THREAD

**Issue by LArayane** [anqixu/mambo_driver#3]
Hi,

Am trying to get pose, velocity and acceleration data of an object given by the vicon system. Am using the package of vrpn_client_ros . Echoing the pos and velocity works good but the node crashes when I try to echo the topic that publish the acceleration and here is the error I get:

  [FATAL] [1594902230.402518999]: ASSERTION FAILED
              file = /opt/ros/kinetic/include/ros/publisher.h
              line = 115
   cond = impl_->md5sum_ == "*" || std::string(mt::md5sum<M>(message)) == "*" || impl_->md5sum_ == mt::md5sum<M>(message)
    message = 
    [FATAL] [1594902230.402655278]: Trying to publish message of type [geometry_msgs/AccelStamped/d8a98a5d81351b6eb0578c78557e7659] on a publisher with type [geometry_msgs/TwistStamped/98d34b0043a2093cf9d9345ab6eef12e]
     [FATAL] [1594902230.402719727]:  [vrpn_client_node-2] process has died [pid 6517, exit code -5, cmd /home/rayane/catkin_ws/devel/lib/vrpn_client_ros/vrpn_client_node __name:=vrpn_client_node __log:=/home/rayane/.ros/log/fe94fc44-c75e-11ea-9b53-48f17fbeed4e/vrpn_client_node-2.log].

log file: /home/rayane/.ros/log/fe94fc44-c75e-11ea-9b53-48f17fbeed4e/vrpn_client_node-2*.log

Any help would be appreciated. thanks

**Comment by anqixu** [comment]
Hmm sorry I fail to see how vrpn_client_ros is related to this package. Perhaps you should check with their developers or on answers.ros.org.
